#!/bin/sh
set -e

case "$1" in
    configure)
        if ! getent group pwldapd >/dev/null; then
            addgroup --system pwldapd
        fi
        if ! getent passwd pwldapd >/dev/null; then
            adduser --system --ingroup pwldapd --no-create-home \
                --shell /usr/sbin/nologin --gecos "pwldapd daemon" pwldapd
        fi
        ;;
esac

#DEBHELPER#
