name: Build release
on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y libpam0g-dev

      - name: Install cargo-deb
        run: cargo install cargo-deb

      - name: Build Debian Package
        run: cargo deb

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: debian-package
          path: target/debian/*.deb

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: target/debian/*.deb
